version: '3'

services:
  web:
    build: rails
    ports:
      - "3000:3000"
    volumes:
      - ./rails:/srv/coral
    env_file:
      - .env/development/database
      - .env/development/web

  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - coral_data:/var/lib/postgresql/data



volumes:
  coral_data:

