version: '3'

services:
  nginx:
    depends_on:
      - web
    image: 'nginx:latest'
    ports: 
      - ${NGINX_PORT:-9000}:80
    volumes:
      - ./nginx:/etc/nginx
    environment:
      - NGINX_PORT=${NGINX_PORT:-9000}

  web:
    build: rails
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ./rails:/srv/coral
      - gem_cache:/var/lib/ruby/gems
    env_file:
      - .env/development/database
      - .env/development/web

  webpacker_dev:
    build: rails
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    volumes:
      - ./rails:/srv/coral
      - gem_cache:/var/lib/ruby/gems
    env_file:
      - .env/development/database
      - .env/development/web
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - "5900:5900"

  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - coral_data:/var/lib/postgresql/data

volumes:
  coral_data:
  gem_cache:
